name: shopify-python

type: python

up:
  - python: 3.9.8
  - python_develop
  - pip: [requirements.txt]

commands:
  lint:
    desc: "Check for Python style & syntax errors in all Python files"
    run: make lint
  test:
    desc: "Run all tests"
    run: make run_tests
